config/routes.rb
Nash::Application.routes.draw do

  root :to => 'content_pages#home'

  get "content_pages/home"

  match '/help', to: 'content_pages#help'

  match '/questions', to: 'content_pages#questions'

  match '/signup', to: 'landlords#new'

  resources :properties

  resources :landlords

end

app/models/landlord.rb
class Landlord < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password

  before_save { |landlord| landlord.email = email.downcase }

  has_many :properties

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true
end

app/models/property.rb
class Property < ActiveRecord::Base
  attr_accessible :address1, :address2, :city, :country, :desiredmonthlyrent, :emergencycontact, :landlord_id, :maxtenantoccupancy, :numberofbathrooms, :numberofbedrooms, :postcode, :propertytype, :sqaurefootage

belongs_to :landlord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/content_pages_controller.rb
class ContentPagesController < ApplicationController
  def home
  end

  def help
  end

  def questions
  end
end

app/controllers/landlords_controller.rb
class LandlordsController < ApplicationController
  # GET /landlords
  # GET /landlords.json
  def index
    @landlords = Landlord.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @landlords }
    end
  end

  # GET /landlords/1
  # GET /landlords/1.json
  def show
    @landlord = Landlord.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @landlord }
    end
  end

  # GET /landlords/new
  # GET /landlords/new.json
  def new
    @landlord = Landlord.new
    render :partial => "new_landlord"
    
  end

  # GET /landlords/1/edit
  def edit
    @landlord = Landlord.find(params[:id])
  end

  # POST /landlords
  # POST /landlords.json
  def create
    @landlord = Landlord.new(params[:landlord])

    respond_to do |format|
      if @landlord.save
        format.html { redirect_to root_path, notice: 'Your account was successfully created.' }
        format.json { render json: @landlord, status: :created, location: @landlord }
      else
        format.html { render :partial => "new_landlord" }
        format.json { render json: @landlord.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /landlords/1
  # PUT /landlords/1.json
  def update
    @landlord = Landlord.find(params[:id])

    respond_to do |format|
      if @landlord.update_attributes(params[:landlord])
        format.html { redirect_to @landlord, notice: 'Landlord was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @landlord.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /landlords/1
  # DELETE /landlords/1.json
  def destroy
    @landlord = Landlord.find(params[:id])
    @landlord.destroy

    respond_to do |format|
      format.html { redirect_to landlords_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController	

  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @properties }
    end
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
    @property = Property.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @property }
    end
  end

  # GET /properties/new
  # GET /properties/new.json
  def new
    @property = Property.new
    render :partial => "new_property"
    
    
  end

  # GET /properties/1/edit
  def edit
    @property = Property.find(params[:id])
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(params[:property])

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render json: @property, status: :created, location: @property }
      else
        format.html { render action: "new" }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /properties/1
  # PUT /properties/1.json
  def update
    @property = Property.find(params[:id])

    respond_to do |format|
      if @property.update_attributes(params[:property])
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property = Property.find(params[:id])
    @property.destroy

    respond_to do |format|
      format.html { redirect_to properties_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/content_pages_helper.rb
module ContentPagesHelper
end

app/helpers/landlords_helper.rb
module LandlordsHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/content_pages/help.html.erb
<h1>ContentPages#help</h1>
<p>Find me in app/views/content_pages/help.html.erb</p>

app/views/content_pages/home.html.erb
<h1>ContentPages#home</h1>

<p id="notice"><%= notice %></p>

<p>Find me in app/views/content_pages/home.html.erb</p>

app/views/landlords/edit.html.erb
<h1>Editing landlord</h1>

<%= render 'form' %>

<%= link_to 'Show', @landlord %> |
<%= link_to 'Back', landlords_path %>

app/views/landlords/index.html.erb
<% provide(:title, 'All Landlords') %>


<head>
	<title<%= yield(:title) %></title)
</head>
<h1>Listing landlords</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @landlords.each do |landlord| %>
  <tr>
    <td><%= landlord.name %></td>
    <td><%= landlord.email %></td>
    <td><%= link_to 'Show', landlord %></td>
    <td><%= link_to 'Edit', edit_landlord_path(landlord) %></td>
    <td><%= link_to 'Destroy', landlord, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Landlord', new_landlord_path %>

app/views/landlords/new.html.erb
<h1>New landlord</h1>

<%= render 'form' %>

<%= link_to 'Back', landlords_path %>

app/views/landlords/show.html.erb
<p id="notice"><%= notice %></p>
<!-- User List Table -->
				<!-- This table can be used for listing things like users -->
				<h2 class="gt-table-head"></h2>
				<!-- Content Box -->
				<div class="gt-content-box">
					<table border="0" class="gt-table gt-user-table">
						<tbody>
							<tr>
								<td class="gt-avatar"><%= image_tag 'gt/avatar.gif', :alt => 'avatar' %></td>
								<td>
									<h4><%= @landlord.name %></h4>
									<p>My favorite color is green. I really like trees!</p>
									
									<p><%= link_to 'Edit', edit_landlord_path(@landlord), :class => 'gt-table-edit' %></p>
								</td>
								<td>
									<!-- Categories Sub Table -->
									<table border="0" class="gt-table-categories">
										<tr>
											<th>Email Address:</th>
											<td><%= @landlord.email %></td>
										</tr>
										<tr>
											<th>Friends:</th>
											<td><a href="">Susan</a>, <a href="">Fred</a></td>
										</tr>
									</table>
								</td>
							</tr>
						</tbody>
					</table>
				</div><!-- /Content Box -->

				<div class="gt-table-buttons">
					<%= link_to 'Back', landlords_path, :class => 'gt-btn-blue-small' %>
				</div>
				
				<!-- / User List -->

app/views/layouts/_header.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
		<title>Gooey Templates : CMS Style App</title>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta http-equiv="Expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
		<meta http-equiv="Pragma" content="no-cache" />
		<%= stylesheet_link_tag 'reset-fonts', :media => "all" %>
		<%= stylesheet_link_tag 'gt-styles', :media => "all" %>

		<!-- Facebox inculdes -->
		<%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js" %>
		<%= javascript_include_tag "facebox.js" %>
		<%= stylesheet_link_tag "facebox.css" %>

	</head>
	<body>
		<!-- head -->
		<div class="gt-hd clearfix">
			<!-- leaf watermark -->
			<div class="gt-leaf-watermark clearfix">
			
			<!-- head top -->
			<div class="gt-hd-top clearfix">
			
				<div class="gt-fixed-wrap clearfix">
			
				<!-- logo -->
				<div class="gt-logo">
					Propertygate <%= image_tag 'gt/leaf-logo-icon.png', :alt => 'leaf-logo-icon' %>
				</div>
				<!-- / logo -->
				
				<!-- utility box -->
				<div class="gt-util-box">
					<div class="gt-util-box-inner">
						<p>welcome <strong>sarah</strong> <span class="gt-util-separator">|</span> <a href="">logout</a></p>
					</div>
				</div>
				<!-- / utility box -->
				
				</div>
			
			</div><!-- /head top -->
			
			<!-- navbar -->
			<div class="gt-navbar clearfix">
				
				<div class="gt-fixed-wrap clearfix">
				
				<!-- navigation -->
				<div class="gt-nav">
					<ul>
						<li><%= link_to "Home", root_path %></a></li>
						<li><%= link_to "Properties & Tenants", properties_path %></li>
						<li><a href="#">Work Orders</a></li>
						<li><a href="#">Marketing</a></li>
						<li><a href="#">Accounting</a></li>
						<li><%= link_to "F.A.Q", questions_path %></li>
					</ul>
				</div><!-- / navigation -->
				
				<!-- search -->
				<div class="gt-search"><div class="gt-search-inner">
					<input type="text" class="gt-search-text" value="Search" onfocus="javascript:if(this.value=='Search')this.value='';" onblur="javascript:if(this.value=='')this.value='Search';" />
				</div></div>
				
				</div>
				
			</div><!-- /navbar -->			
		</div><!-- /leaf watermark -->
		</div>
		<!-- / head -->

app/views/layouts/_new_property.html.erb
 <%= form_for(@property) do |f| %>
  <% if @property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% @property.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
        
        <div class="gt-form gt-content-box">
          <div class="clearfix">
            <!-- left column -->
            <div class="gt-left-col">
              <!-- form row -->
              <div class="gt-form-row gt-width-66">
                <label>Address 1</label>
                <%= f.text_field :address1, :class => 'gt-form-text' %>
              </div><!-- /form row -->
           
              <!-- form row -->
              <div class="gt-form-row gt-width-66">
                <label>Address 2</label>
                <%= f.text_field :address2, :class => 'gt-form-text' %>
              </div><!-- /form row -->
              
              <!-- form row -->
              <div class="gt-form-row gt-width-66">
                <label>City</label>
                <%= f.text_field :city, :class => 'gt-form-text' %>
              </div><!-- /form row -->
              
              <!-- form row -->
              <div class="gt-form-row gt-width-66">
                <label>Post Code</label>
                <%= f.text_field :postcode, :class => 'gt-form-text' %>
              </div><!-- /form row -->
              
              <!-- form row -->
              <div class="gt-form-row gt-width-66">
                <label>Country</label>
                <%= f.text_field :country, :class => 'gt-form-text' %>
              </div><!-- /form row -->
            </div>
            
            <!-- right column -->
            <div class="gt-right-col">
              <!-- form row -->
              <div class="gt-form-row gt-width-66 clearfix">
                <label>Property Type</label>
                <%= f.select "propertytype", options_for_select([ "Bunglow", "Terrace", "End of Terrace", "Semi-Detached", "Detached" ]) %>
              </div>
              <!-- /form row -->
              
              <!-- form row -->
              <div class="gt-form-row gt-width-66 clearfix">
                <label># of Bedrooms</label>
                <%= f.select "numberofbedrooms", options_for_select([ "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" ]) %>
              </div><!-- /form row -->
            
              <!-- form row -->
              <div class="gt-form-row gt-width-66 clearfix">
                <label># Bathrooms</label>
                <%= f.select "numberofbathrooms", options_for_select([ "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" ]) %>
              </div>
              <!-- /form row -->
              
              <!-- form row -->
              <div class="gt-form-row gt-width-66 clearfix">
                <label>Square Footage</label>
                <%= f.text_field :sqaurefootage, :class => 'gt-form-text' %>
              </div>
              <!-- /form row -->
              
              <!-- form row -->
              <div class="gt-form-row gt-width-66 clearfix">
                <label>Max Tenant Occupancy</label>
                <%= f.text_field :maxtenantoccupancy, :class => 'gt-form-text' %>
              </div>
              <!-- /form row -->
              
              <!-- form row -->
              <div class="gt-form-row gt-width-66 clearfix">
                <label>Desired Monthly Rent</label>
                <%= f.text_field :desiredmonthlyrent, :class => 'gt-form-text' %>
              </div>
              <!-- /form row -->
            </div>
          </div>
          <!-- form row -->
          <div class="gt-form-row">
            <%= f.submit 'Save', :class => 'gt-btn-blue-small gt-btn-left' %>
            <% end %>
            <p class="gt-cancel">or <%= link_to 'Back', properties_path %></p>
          </div>
          
          
          
      

          <!-- /form row -->
          
        </div>
        <!-- /Add / Edit User Form -->
      </div>
      <!-- / main content -->

app/views/layouts/_property_sidebar.html.erb
<div class="gt-sidebar">
				<!-- Sidebar Navigation -->
				<div class="gt-sidebar-nav gt-sidebar-nav-blue">
					<h3>Quick Links</h3>
					<ul>
						<li><%= link_to 'Add a New Property', new_property_path, :rel => 'facebox' %></li>
						<li><a href="">Edit User Settings</a></li>
						<li><a href="">View Live Site</a></li>
					</ul>
				</div><!-- /Sidebar Navigation -->
				
				<!-- Sidebar Box -->
				<div class="gt-sidebar-box gt-sidebar-box-gray">
					<!-- search -->
					<div class="gt-search"><div class="gt-search-inner">
						<input type="text" class="gt-search-text" value="Find an Article" onfocus="javascript:if(this.value=='Find an Article')this.value='';" onblur="javascript:if(this.value=='')this.value='Find an Article';" />
					</div></div><!-- /search -->
				</div><!-- /Sidebar Box -->
				
				<!-- Sidebar Navigation -->
				<div class="gt-sidebar-nav gt-sidebar-nav-gray">
					<h3>Get Help</h3>
					<ul>
						<li><a href="mailto:help@gooeytemplates.com">Email Us</a></li>
					</ul>
				</div><!-- /Sidebar Navigation -->
				
				<!-- Sidebar Content -->
				<div class="gt-sidebar-content">
					<h3>Sidebar Note</h3>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
				</div><!-- /Sidebar Content -->
				
				<!-- Sidebar List -->
				<div class="gt-sidebar-list">
					<h3>Users List</h3>
					<ul class="gt-sidebar-list-content">
						<li class="gt-sidebar-list-row">
							<%= image_tag 'gt/avatar-small.gif', :class => 'gt-avatar-small' %>
							<h4><a href="">John Marker</a></h4>
							<p>I love to color pictures!</p>
						</li>
						
						<li class="gt-sidebar-list-row">
							<%= image_tag 'gt/avatar-small.gif', :class => 'gt-avatar-small' %>
							<h4><a href="">Charlee Watts</a></h4>
							<p>Eco-friendly is the way to go!</p>
						</li>
						
						<li class="gt-sidebar-list-row">
							<%= image_tag 'gt/avatar-small.gif', :class => 'gt-avatar-small' %>
							<h4><a href="">Sarah Smith</a></h4>
							<p>I love to draw...</p>
						</li>
					</ul>
				</div><!-- /Sidebar List -->
				
			</div>

app/views/layouts/new_property.html.erb
 <%= form_for(@property) do |f| %>
  <% if @property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% @property.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
        
        <div class="gt-form gt-content-box">
          <div class="clearfix">
            <!-- left column -->
            <div class="gt-left-col">
              <!-- form row -->
              <div class="gt-form-row gt-width-66">
                <label>Address 1</label>
                <%= f.text_field :address1, :class => 'gt-form-text' %>
              </div><!-- /form row -->
           
              <!-- form row -->
              <div class="gt-form-row gt-width-66">
                <label>Address 2</label>
                <%= f.text_field :address2, :class => 'gt-form-text' %>
              </div><!-- /form row -->
              
              <!-- form row -->
              <div class="gt-form-row gt-width-66">
                <label>City</label>
                <%= f.text_field :city, :class => 'gt-form-text' %>
              </div><!-- /form row -->
              
              <!-- form row -->
              <div class="gt-form-row gt-width-66">
                <label>Post Code</label>
                <%= f.text_field :postcode, :class => 'gt-form-text' %>
              </div><!-- /form row -->
              
              <!-- form row -->
              <div class="gt-form-row gt-width-66">
                <label>Country</label>
                <%= f.text_field :country, :class => 'gt-form-text' %>
              </div><!-- /form row -->
            </div>
            
            <!-- right column -->
            <div class="gt-right-col">
              <!-- form row -->
              <div class="gt-form-row gt-width-66 clearfix">
                <label>Property Type</label>
                <%= f.select "propertytype", options_for_select([ "Bunglow", "Terrace", "End of Terrace", "Semi-Detached", "Detached" ]) %>
              </div>
              <!-- /form row -->
              
              <!-- form row -->
              <div class="gt-form-row gt-width-66 clearfix">
                <label># of Bedrooms</label>
                <%= f.select "numberofbedrooms", options_for_select([ "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" ]) %>
              </div><!-- /form row -->
            
              <!-- form row -->
              <div class="gt-form-row gt-width-66 clearfix">
                <label># Bathrooms</label>
                <%= f.select "numberofbathrooms", options_for_select([ "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" ]) %>
              </div>
              <!-- /form row -->
              
              <!-- form row -->
              <div class="gt-form-row gt-width-66 clearfix">
                <label>Square Footage</label>
                <%= f.text_field :sqaurefootage, :class => 'gt-form-text' %>
              </div>
              <!-- /form row -->
              
              <!-- form row -->
              <div class="gt-form-row gt-width-66 clearfix">
                <label>Max Tenant Occupancy</label>
                <%= f.text_field :maxtenantoccupancy, :class => 'gt-form-text' %>
              </div>
              <!-- /form row -->
              
              <!-- form row -->
              <div class="gt-form-row gt-width-66 clearfix">
                <label>Desired Monthly Rent</label>
                <%= f.text_field :desiredmonthlyrent, :class => 'gt-form-text' %>
              </div>
              <!-- /form row -->
            </div>
          </div>
          <!-- form row -->
          <div class="gt-form-row">
            <%= f.submit 'Save', :class => 'gt-btn-blue-small gt-btn-left' %>
            <% end %>
            <p class="gt-cancel">or <%= link_to 'Back', properties_path %></p>
          </div>
          
          
          
      

          <!-- /form row -->
          
        </div>
        <!-- /Add / Edit User Form -->
      </div>
      <!-- / main content -->

app/views/properties/_new_property.html.erb
 <%= form_for(@property) do |f| %>
  <% if @property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% @property.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
        
        <div class="gt-form gt-content-box">
          <div class="clearfix">
            <!-- left column -->
            <div class="gt-left-col">
              <!-- form row -->
              <div class="gt-form-row gt-width-66">
                <label>Address 1</label>
                <%= f.text_field :address1, :class => 'gt-form-text' %>
              </div><!-- /form row -->
           
              <!-- form row -->
              <div class="gt-form-row gt-width-66">
                <label>Address 2</label>
                <%= f.text_field :address2, :class => 'gt-form-text' %>
              </div><!-- /form row -->
              
              <!-- form row -->
              <div class="gt-form-row gt-width-66">
                <label>City</label>
                <%= f.text_field :city, :class => 'gt-form-text' %>
              </div><!-- /form row -->
              
              <!-- form row -->
              <div class="gt-form-row gt-width-66">
                <label>Post Code</label>
                <%= f.text_field :postcode, :class => 'gt-form-text' %>
              </div><!-- /form row -->
              
              <!-- form row -->
              <div class="gt-form-row gt-width-66">
                <label>Country</label>
                <%= f.text_field :country, :class => 'gt-form-text' %>
              </div><!-- /form row -->
            </div>
            
            <!-- right column -->
            <div class="gt-right-col">
              <!-- form row -->
              <div class="gt-form-row gt-width-66 clearfix">
                <label>Property Type</label>
                <%= f.select "propertytype", options_for_select([ "Bunglow", "Terrace", "End of Terrace", "Semi-Detached", "Detached" ]) %>
              </div>
              <!-- /form row -->
              
              <!-- form row -->
              <div class="gt-form-row gt-width-66 clearfix">
                <label># of Bedrooms</label>
                <%= f.select "numberofbedrooms", options_for_select([ "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" ]) %>
              </div><!-- /form row -->
            
              <!-- form row -->
              <div class="gt-form-row gt-width-66 clearfix">
                <label># Bathrooms</label>
                <%= f.select "numberofbathrooms", options_for_select([ "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" ]) %>
              </div>
              <!-- /form row -->
              
              <!-- form row -->
              <div class="gt-form-row gt-width-66 clearfix">
                <label>Square Footage</label>
                <%= f.text_field :sqaurefootage, :class => 'gt-form-text' %>
              </div>
              <!-- /form row -->
              
              <!-- form row -->
              <div class="gt-form-row gt-width-66 clearfix">
                <label>Max Tenant Occupancy</label>
                <%= f.text_field :maxtenantoccupancy, :class => 'gt-form-text' %>
              </div>
              <!-- /form row -->
              
              <!-- form row -->
              <div class="gt-form-row gt-width-66 clearfix">
                <label>Desired Monthly Rent</label>
                <%= f.text_field :desiredmonthlyrent, :class => 'gt-form-text' %>
              </div>
              <!-- /form row -->
            </div>
          </div>
          <!-- form row -->
          <div class="gt-form-row">
            <%= f.submit 'Save', :class => 'gt-btn-blue-small gt-btn-left' %>
            <% end %>
            <p class="gt-cancel">or <%= link_to 'Back', properties_path %></p>
          </div>
          
          
          
      

          <!-- /form row -->
          
        </div>
        <!-- /Add / Edit User Form -->
      </div>
      <!-- / main content -->

app/views/properties/edit.html.erb
<h1>Editing property</h1>

<%= render 'form' %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index-old.html.erb
<h1>Listing properties</h1>

<table>
  <tr>
    <th>Address1</th>
    <th>Address2</th>
    <th>City</th>
    <th>Postcode</th>
    <th>Country</th>
    <th>Propertytype</th>
    <th>Emergencycontact</th>
    <th>Numberofbedrooms</th>
    <th>Sqaurefootage</th>
    <th>Maxtenantoccupancy</th>
    <th>Desiredmonthlyrent</th>
    <th>Numberofbathrooms</th>
    <th>Landlord</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @properties.each do |property| %>
  <tr>
    <td><%= property.address1 %></td>
    <td><%= property.address2 %></td>
    <td><%= property.city %></td>
    <td><%= property.postcode %></td>
    <td><%= property.country %></td>
    <td><%= property.propertytype %></td>
    <td><%= property.emergencycontact %></td>
    <td><%= property.numberofbedrooms %></td>
    <td><%= property.sqaurefootage %></td>
    <td><%= property.maxtenantoccupancy %></td>
    <td><%= property.desiredmonthlyrent %></td>
    <td><%= property.numberofbathrooms %></td>
    <td><%= property.landlord_id %></td>
    <td><%= link_to 'Show', property %></td>
    <td><%= link_to 'Edit', edit_property_path(property) %></td>
    <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Property', new_property_path %>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Address1:</b>
  <%= @property.address1 %>
</p>

<p>
  <b>Address2:</b>
  <%= @property.address2 %>
</p>

<p>
  <b>City:</b>
  <%= @property.city %>
</p>

<p>
  <b>Postcode:</b>
  <%= @property.postcode %>
</p>

<p>
  <b>Country:</b>
  <%= @property.country %>
</p>

<p>
  <b>Propertytype:</b>
  <%= @property.propertytype %>
</p>

<p>
  <b>Emergencycontact:</b>
  <%= @property.emergencycontact %>
</p>

<p>
  <b>Numberofbedrooms:</b>
  <%= @property.numberofbedrooms %>
</p>

<p>
  <b>Sqaurefootage:</b>
  <%= @property.sqaurefootage %>
</p>

<p>
  <b>Maxtenantoccupancy:</b>
  <%= @property.maxtenantoccupancy %>
</p>

<p>
  <b>Desiredmonthlyrent:</b>
  <%= @property.desiredmonthlyrent %>
</p>

<p>
  <b>Numberofbathrooms:</b>
  <%= @property.numberofbathrooms %>
</p>

<p>
  <b>Landlord:</b>
  <%= @property.landlord_id %>
</p>


<%= link_to 'Edit', edit_property_path(@property) %> |
<%= link_to 'Back', properties_path %>